
- hosts: localhost
  vars:
    current_user: "{{ working_user }}"
  #become: false
  become: true
  become_user: "{{ current_user }}"
  become_method: sudo
  tasks:
  - name: Test
    debug: msg="{{ ansible_env.USER }}"

  - name: Add stretch backports repo
    apt_repository:
      repo: deb http://deb.debian.org/debian stretch-backports main contrib
      state: present
      filename: stretch-backports.list

  - name: "apt-get update"
    apt:
      update_cache: yes

  - name: Install tor
    apt:
      name: tor
      state: latest

  - name: Install Gajim with OMEMO support
    apt: name={{item}} state=installed
    with_items:
      - gajim
      - gajim-omemo
      - gajim-httpupload
      - gajim-urlimagepreview
      - gajim-triggers

  - name: Install Thunderbird, Enigmail, TorBirdy
    apt: name={{item}} state=installed
    with_items:
      - thunderbird
      - enigmail
      - torbirdy

  - name: Install Tor-Browser
    apt:
      name: torbrowser-launcher
      state: latest
      default_release: stretch-backports

  - name: wget test
    get_url:
      url: "https://github.com/nebulak/riot-sh/raw/master/riot.sh"
      dest: "/usr/bin/riot.sh"
      mode: 0755


  - name: Install Keepassxc
    get_url:
      url: "https://github.com/keepassxreboot/keepassxc/releases/download/2.3.3/KeePassXC-2.3.3-x86_64.AppImage"
      dest: "/usr/bin/keepassxc"
      mode: 0755

#  - name: Install AppImaged
#    get_url:
#      url: "https://github.com/AppImage/appimaged/releases/download/continuous/appimaged-x86_64.AppImage"
#      dest: "/home/{{ ansible_env.USER }}/.riot-sh/appimaged-x86_64.AppImage"

  - name: Install Firejail
    apt:
      name: firejail
      state: latest

  - name: Install Torjail
    get_url:
      url: "https://raw.githubusercontent.com/torjail/torjail/master/torjail"
      dest: "/home/{{ ansible_env.USER }}/bin/torjail"

#  - name: Add DNSCrypt-Proxy ppa
#    apt_repository:
#      repo: 'ppa:shevchuk/dnscrypt-proxy'
#      codename: xenial
#      state: present

#  - name: Install DNSCrypt-Proxy
#    apt:
#      name: dnscrypt-proxy
#      state: latest

  #- name: Install restic for encrypted backups
    # TODO: https://github.com/restic/restic/releases/tag/v0.8.3

# //TODO: Install tool to setup smartcard for full-disk-encryption
# //TODO: - name: Use gajim only with tor using torjail
