
- hosts: localhost
  vars:
    current_user: "{{ working_user }}"
  #become: false
  become: true
  #become_user: "{{ current_user }}"
  become_method: sudo
  tasks:

  - name: Install apt-transport-https
    apt:
      name: apt-transport-https
      state: latest

  - name: setup debian sid repository
    apt_repository:
      repo: deb http://ftp.ch.debian.org/debian sid main contrib non-free
      state: present

  - name: Add stretch backports repo
    apt_repository:
      repo: deb http://deb.debian.org/debian stretch-backports main contrib
      state: present
      filename: stretch-backports.list

  - name: Create .riot-sh directory
    become: yes
    become_user: "{{ current_user }}"
    file: path="/home/{{ current_user }}/.riot-sh" state=directory

  - name: Create .riot-sh/temp directory
    become: yes
    become_user: "{{ current_user }}"
    file: path="/home/{{ current_user }}/.riot-sh/temp" state=directory

  - name: "apt-get update"
    apt:
      update_cache: yes

  - name: Install tor
    apt:
      name: tor
      state: latest

  - name: Install bzip2
    apt:
      name: bzip2
      state: latest

  - name: Install Dino.im
    apt:
      name: torbrowser-launcher
      state: latest
      default_release: sid
  
  - name: Install qBittorrent
    apt:
      name: qbittorrent
      state: latest
      default_release: sid


  - name: Install Thunderbird, Enigmail, TorBirdy
    apt: name={{item}} state=installed
    with_items:
      - thunderbird
      - enigmail
      - torbirdy

  - name: Install Tor-Browser
    apt:
      name: torbrowser-launcher
      state: latest
      default_release: stretch-backports

  # https://www.privacy-handbuch.de/download/moderat/user.js
  - name: Add secure user.js file to firefox
    become: yes
    become_user: "{{ current_user }}"
    find:
      paths: "/home/{{ current_user }}/.mozilla/firefox"
      patterns: "*.default"
      register: firefox_profile_paths
      
  - name: copy user.js file to firefox default profile
    become: yes
    become_user: "{{ current_user }}"
    get_url:
      url: https://www.privacy-handbuch.de/download/moderat/user.js
      dest: "{{ firefox_profile_paths.directories[0].path }}"
  
  - name: add https-everywhere
    apt:
      name: xul-ext-https-everywhere
      state: latest
      default_release: sid

  - name: add privacy-badger
    apt:
      name: webext-privacy-badger
      state: latest
      default_release: sid
      
  - name: add uBlock Origin
    apt:
      name: webext-ublock-origin
      state: latest
      default_release: sid

  - name: Setup gnupg.conf
    become: yes
    become_user: "{{ current_user }}"
    get_url:
      url: "https://raw.githubusercontent.com/ioerror/duraconf/master/configs/gnupg/gpg.conf"
      dest: "/home/{{ current_user }}/.gnupg/gpg.conf"
      mode: 0700
  
  - name: Setup gpg-agent.conf
    become: yes
    become_user: "{{ current_user }}"
    get_url:
      url: "https://gist.githubusercontent.com/nebulak/2d8a842b28c9749393bcb0c416744948/raw/6afe7af5d7fb9486f458e6e9093bfe3ac43d1570/gpg-agent.conf"
      dest: "/home/{{ current_user }}/.gnupg/gpg-agent.conf"
      mode: 0700

  - name: Install syncthing
    apt:
      name: syncthing
      state: latest
      default_release: syncthing
    
  - name: Install KeePassXC
    apt: 
      name: keepassxc 
      state: latest
      default_release: sid
  
  - name: Install gocryptfs
    apt: 
      name: gocryptfs
      state: latest
      default_release: sid

#  - name: Install mozilla-extension-manager
#    become: yes
#    get_url:
#      url: "https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/mozilla/mozilla-extension-manager"
#      dest: "/usr/local/sbin/mozilla-extension-manager"
#      mode: 0755
  
#  - name: Install KeePassXC-Browser for Firefox
#    become: yes
#    become_user: "{{ current_user }}"
#    command: mozilla-extension-manager --install https://addons.mozilla.org/firefox/downloads/latest/1101197/keepassxc_browser-1.3.0-fx.xpi
    

  - name: Install Magic-Wormhole
    apt:
      name: magic-wormhole
      state: latest

  - name: Install Torjail
    become: yes
    become_user: "{{ current_user }}"
    get_url:
      url: "https://raw.githubusercontent.com/torjail/torjail/master/torjail"
      dest: "/home/{{ current_user }}/bin/torjail"


  - name: Install restic
    apt: 
      name: restic
      state: latest
      default_release: sid


# STYLE

  - name: Install arc-dark theme
    apt: name={{item}} state=installed
    with_items:
      - arc-theme

  - name: Setup arc dark theme for gtk
    become: yes
    become_user: "{{ current_user }}"
    shell: gsettings set org.gnome.desktop.interface gtk-theme "arc-dark"
  
  - name: Setup arc dark theme for windows
    become: yes
    become_user: "{{ current_user }}"
    shell: gsettings set org.gnome.desktop.wm.preferences theme "arc-dark"
  
  - name: install flat remix icons
    become: yes
    become_user: "{{ current_user }}"
    shell: cd /tmp && rm -rf flat-remix && git clone https://github.com/daniruiz/flat-remix && mkdir -p ~/.icons && cp -r flat-remix/Flat-Remix* ~/.icons/

  - name: setup flat remix icons
    become: yes
    become_user: "{{ current_user }}"
    shell: gsettings set org.gnome.desktop.interface icon-theme "Flat-Remix"

  - name: add whisker-menu
    apt: name={{item}} state=installed
    with_items:
      - xfce4-whiskermenu-plugin
# //TODO: https://wiki.ubuntuusers.de/Whisker_Menu/#Systemweite-Nutzung


