
- hosts: localhost
  vars:
    current_user: "{{ working_user }}"
  #become: false
  become: true
  #become_user: "{{ current_user }}"
  become_method: sudo
  tasks:

  - name: Install apt-transport-https
    apt:
      name: apt-transport-https
      state: latest

  - name: Add stretch backports repo
    apt_repository:
      repo: deb http://deb.debian.org/debian stretch-backports main contrib
      state: present
      filename: stretch-backports.list

  - name: Add syncthing Apt Key
    apt_key:
      url: https://syncthing.net/release-key.txt
      state: present

  - name: Add syncthing repo
    apt_repository:
      repo: deb https://apt.syncthing.net/ syncthing stable
      state: present
      filename: syncthing.list



  - name: "apt-get update"
    apt:
      update_cache: yes

  - name: Install tor
    apt:
      name: tor
      state: latest

  - name: Install bzip2
    apt:
      name: bzip2
      state: latest

  - name: Install Gajim with OMEMO support
    apt: name={{item}} state=installed
    with_items:
      - gajim
      - gajim-omemo
      - gajim-httpupload
      - gajim-urlimagepreview
      - gajim-triggers

  - name: Install Thunderbird, Enigmail, TorBirdy
    apt: name={{item}} state=installed
    with_items:
      - thunderbird
      - enigmail
      - torbirdy

  - name: Install Tor-Browser
    apt:
      name: torbrowser-launcher
      state: latest
      default_release: stretch-backports

  - name: Install syncthing
    apt:
      name: syncthing
      state: latest
      default_release: syncthing

  - name: Install onion gajim
    get_url:
      url: "https://github.com/nebulak/onion-gajim/raw/master/onion-gajim"
      dest: "/usr/bin/onion-gajim"
      mode: 0755

  - name: Create onion gajim desktop-file
    get_url:
      url: "https://github.com/nebulak/onion-gajim/raw/master/onion-gajim.desktop"
      dest: "/usr/share/applications/onion-gajim.desktop"
      mode: 0755

  - name: Install onion-gajim desktop file
    shell: desktop-file-install "/usr/share/applications/onion-gajim.desktop"


  - name: Download KeeWeb for i386
    become: yes
    become_user: "{{ current_user }}"
    when: ansible_architecture == "i386"
    get_url:
      url: "https://github.com/keeweb/keeweb/releases/download/v1.6.3/KeeWeb-1.6.3.linux.ia32.deb"
      dest: "/home/{{ current_user }}/bin/keeweb.deb"
      mode: 0755

  - name: Download KeeWeb for x86_64
    become: yes
    become_user: "{{ current_user }}"
    when: ansible_architecture == "x86_64"
    get_url:
      url: "https://github.com/keeweb/keeweb/releases/download/v1.6.3/KeeWeb-1.6.3.linux.x64.deb"
      dest: "/home/{{ current_user }}/bin/keeweb.deb"
      mode: 0755

  - name: Install KeeWeb .deb package
    apt:
      deb: /tmp/riotsh/keeweb.deb

  - name: Download gocryptfs for x86_64
    become: yes
    become_user: "{{ current_user }}"
    when: ansible_architecture == "x86_64"
    get_url:
      url: "https://github.com/rfjakob/gocryptfs/releases/download/v1.4.4/gocryptfs_v1.4.4_linux-static_amd64.tar.gz"
      dest: "/home/{{ current_user }}/bin/gocryptfs.tar.gz"
      mode: 0755

  - name: extract gocryptfs for x86_64
    become: yes
    become_user: "{{ current_user }}"
    when: ansible_architecture == "x86_64"
    unarchive:
      src: "/home/{{ current_user }}/bin/gocryptfs.tar.gz"
      dest: "/home/{{ current_user }}/bin"
      remote_src: yes

  - name: Install Firejail
    apt:
      name: firejail
      state: latest

  - name: Install Firetools
    apt:
      name: firetools
      state: latest

  - name: Install Magic-Wormhole
    apt:
      name: magic-wormhole
      state: latest

  - name: Install Torjail
    become: yes
    become_user: "{{ current_user }}"
    get_url:
      url: "https://raw.githubusercontent.com/torjail/torjail/master/torjail"
      dest: "/home/{{ current_user }}/bin/torjail"


  - name: Install restic for x86_64
    become: yes
    become_user: "{{ current_user }}"
    when: ansible_architecture == "x86_64"
    get_url:
      url: https://github.com/restic/restic/releases/download/v0.9.0/restic_0.9.0_linux_amd64.bz2
      dest: "/home/{{ current_user }}/bin/restic_0.9.0.bz2"

  - name: Install restic for x86
    become: yes
    become_user: "{{ current_user }}"
    when: ansible_architecture == "i386"
    get_url:
      url: https://github.com/restic/restic/releases/download/v0.9.0/restic_0.9.0_linux_386.bz2
      dest: "/home/{{ current_user }}/bin/restic_0.9.0.bz2"

  - name: Unpack restic
    become: yes
    become_user: "{{ current_user }}"
    shell: bzip2 -d "/home/{{ current_user }}/bin/restic_0.9.0.bz2"

  - name: Rename restic binary
    become: yes
    become_user: "{{ current_user }}"
    shell: mv "/home/{{ current_user }}/bin/restic_0.9.0" "/home/{{ current_user }}/bin/restic"

  - name: Make restic binary executable
    become: yes
    become_user: "{{ current_user }}"
    shell: chmod +x "/home/{{ current_user }}/bin/restic"

# //TODO: Install tool to setup smartcard for full-disk-encryption
# //TODO: - name: Use gajim only with tor using torjail
